version: '3'
services:
  gemini:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    container_name: gemini
    expose:
      - '1234'
    ports:
      - '1234:1234'
    command: npm run start
