const attribut2UserName = {
    libelle_adr_principale_ban: "Adresse",
    fiabilite_cr_adr_niv_1: "Fiabilité de l'adresse ",
    code_iris: "Code IRIS",
    libelle_commune_insee: "Commune",
    code_departement_insee: "Numéro de département",
    bdtopo_zoa_l_toponyme: "Toponyme",
    code_commune_insee: "Code INSEE",

    ffo_bat_annee_construction: "Date de construction",
    ETAT: "État du bâtiment",
    NATURE: "Nature",
    ffo_bat_usage_niveau_1_txt: "Usage",
    USAGE1: "Usage",
    USAGE2: "Usage",
    bdtopo_bat_altitude_sol_mean: "Altitude au sol",
    bdtopo_bat_hauteur_mean: "Hauteur du bâtiment",
    NB_ETAGES: "Nombre d'étages",

    argiles_alea: "Risque argile",
    radon_alea: "Risque radon",

    dpe_arrete_2021_nb_classe_conso_energie_arrete_2012: "Notes énergétique des logements",
    dpe_nb_classe_ener_a: "Notes énergétique des logements",
    dpe_nb_classe_ener_b: "Notes énergétique des logements",
    dpe_nb_classe_ener_c: "Notes énergétique des logements",
    dpe_nb_classe_ener_d: "Notes énergétique des logements",
    dpe_nb_classe_ener_e: "Notes énergétique des logements",
    dpe_nb_classe_ener_f: "Notes énergétique des logements",
    dpe_nb_classe_ener_g: "Notes énergétique des logements",
    dpe_nb_classe_ener_nc: "Notes énergétique des logements",
    dpe_nb_classe_ges_a: "Notes énergétique des logements",
    dpe_nb_classe_ges_b: "Notes énergétique des logements",
    dpe_nb_classe_ges_c: "Notes énergétique des logements",
    dpe_nb_classe_ges_d: "Notes énergétique des logements",
    dpe_nb_classe_ges_e: "Notes énergétique des logements",
    dpe_nb_classe_ges_f: "Notes énergétique des logements",
    dpe_nb_classe_ges_g: "Notes énergétique des logements",
    dpe_nb_classe_ges_nc: "Notes énergétique des logements",
    dpe_class_conso_ener_mean: "Notes énergétique des logements",
    dpe_conso_ener_mean: "Notes énergétique des logements",
    dpe_conso_ener_std: "Notes énergétique des logements",
    dpe_class_estim_ges_mean: "Notes énergétique des logements",
    dpe_estim_ges_mean: "Notes énergétique des logements",
    dpe_estim_ges_std: "Notes énergétique des logements",
    dpe_logtype_mur_pos_isol_ext: "Notes énergétique des logements",
    dpe_logtype_pb_pos_isol: "Notes énergétique des logements",
    dpe_logtype_ph_pos_isol: "Notes énergétique des logements",
}


